name: Install Executable
description: |-
  Install an executable into the PATH given a source S3 bucket.
  The executable MUST be have at the following name:
    s3://${s3_bucket}[/${prefix}]/${executable}/${checksum}
  Where the ${checksum} is the checksum of the executable itself
inputs:
  bucket:
    description: S3 Bucket name to download from (no "s3://" prefix)
    required: true
  prefix:
    description: S3 Prefix of the binary folder
    required: false
    default: "bin"
  executable:
    description: The name of the executable to [download and] install
    required: true
  algorithm:
    description: |-
      The hash algorithm used to validate downloaded executable.
      For all possible algorithms, see the 'cksum' command.
      Note that only secure algorithms are supported.
    required: false
    default: SHA256
  checksum:
    description: The checksum of the file to download
    required: true

runs:
  using: "composite"
  steps:
    - id: create_install_dir
      shell: bash
      run: |
        install_dir="$(mktemp -d -t 'github-actions.install-executable.${{ inputs.executable }}.XXXXXXXXXXXXXXXX')"
        echo "::debug:: Created temporary directory: ${install_dir}"
        echo "::set-output name=dir_name::${install_dir}"

    - id: check_command
      shell: bash
      run: |
        command -v "cksum"
        cksum --version

    - id: check_algorithm
      shell: bash
      run: |
        echo "::debug:: Requested algorithm '${{ inputs.algorithm }}' for checksum verification"

        case '${{ inputs.algorithm }}' in
          'SHA512' | 'SHA384' | 'SHA256' | 'SHA224' | 'BLAKE2b' )
            # OK
            ;;
          'BSD' | 'SYSV' | 'CRC' | 'MD5' | 'SHA1' | 'SM3' )
            echo "::error:: Insecure algorithm '${{ inputs.algorithm }}' is not allowed to be selected"
            exit 1
            ;;
          * )
            echo "::error:: Unsupported algorithm '${{ inputs.algorithm }}'"
            exit 2
            ;;
        esac

    - id: download_executable
      shell: bash
      run: |
        S3_BUCKET='${{ inputs.bucket }}'
        S3_BUCKET="${S3_BUCKET##'s3://'}"  # remove "s3://" prefix if provided
        S3_BUCKET="${S3_BUCKET%'/'}"  # remove trailing '/' if provided
        S3_PREFIX='${{ inputs.prefix }}'
        EXECUTABLE='${{ inputs.executable }}'
        CHECKSUM='${{ inputs.checksum }}'
        FINAL_S3_PREFIX="${S3_PREFIX:+${S3_PREFIX}/}${EXECUTABLE}"
        FINAL_PATH="$(printf 's3://%s/%s/%s' "${S3_BUCKET}" "${FINAL_S3_PREFIX}" "${CHECKSUM}" )"
        echo "::debug:: Full S3 path is ${FINAL_PATH}"
        aws s3 cp "${FINAL_PATH}" '${{ steps.create_install_dir.outputs.dir_name }}'

    - id: validate_checksum
      shell: bash
      env:
        # Format for a tagged checksum is: ALGORITHM (FILENAME) = CHECKSUM
        # e.g., SHA512 (/tmp/github-actions.install-executable.example.XXXXXXXXXXXXXXXX/example_checksum) = example_checksum
        # Validate using `cksum -c -` (the `-c` means "check", the second `-` means read from STDIN)
        expected_tagged_value: '${{ inputs.algorithm }} (${{ steps.create_install_dir.outputs.dir_name }}/${{ inputs.checksum }}) = ${{ inputs.checksum }}'
      run: |
        echo "::debug:: Expected value: ${{ env.expected_tagged_value }}"
        printf '${{ env.expected_tagged_value }}' | cksum -c -

    - id: add_to_path
      shell: bash
      run: |
        pushd '${{ steps.create_install_dir.outputs.dir_name }}'
        mv '${{ inputs.checksum }}' '${{ inputs.executable }}'
        chmod 0555 '${{ inputs.executable }}'
        popd
        echo '${{ steps.create_install_dir.outputs.dir_name }}' >> "${GITHUB_PATH}"

    # Validate installation in succeeded in another step. According to the documentation,
    # > The current running action can not access the updated path variable
    # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
    - id: validate_install
      shell: bash
      run: |
        if ! command -v '${{ inputs.executable }}' &> /dev/null
        then
          echo "::error:: Could not find '${{ inputs.executable }}' in the path even after installation"
          echo "::info:: PATH: ${PATH}"
          cat ${GITHUB_PATH}
          exit 3
        fi
