AWSTemplateFormatVersion: 2010-09-09
Description: Deploy the IAM Custom Role Service Catalog Product.
Parameters:
  RoleNameSuffix:
    Type: String
    Description: Name of custom Role appended to TeamName-custom-
  ManagedPolicyArns:
    Type: String
    Description: Comma delimited list of Managed IAM Policy ARNs to attach to the Role (but marked as String). Please be aware these ARNs are account specific. In this example we are providing the format for an ARN of the IAM::Policy that was created providing permissions to RedShift
  AssumingServices:
    Type: String
    Description: Comma delimited list of Services that needs to assume the role (but marked as String)
    Default: ""
  AssumingRoles:
    Type: String
    Description: Comma delimited list of Services that needs to assume the role (but marked as String)
    Default: ""

Resources:
  IAMRole:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: IAMRole
      ProvisioningArtifactName: 1.2.0
      ProvisionedProductName: !Sub ${RoleNameSuffix}-role
      ProvisioningParameters:
        - Key: AssumingServices
          Value: !Ref AssumingServices
        - Key: AssumingRoles
          Value: !Ref AssumingRoles
        - Key: RoleNameSuffix
          Value: !Ref RoleNameSuffix
        - Key: ManagedPolicyArns
          Value:
            !Join [
              ",",
              [
                !Ref ManagedPolicyArns,
                !Sub "arn:aws:iam::${AWS::AccountId}:policy/AllowResourcesAccessToCloudWatchPolicy",
              ],
            ]

      Tags:
        - Key: doNotShutDown
          # change to false if it can be turned off outside of business hours
          Value: "true"

Outputs:
  StackArn:
    Value: !GetAtt IAMRole.CloudformationStackArn
    Description: The ARN of the created cloud formation stack
