name: Repository Dev Workflow

on:
  pull_request_target:
    types: [opened]


jobs:
  tartufo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo on to a job runner.
        run: echo "Checkout this repo on to a job runner."
      - name: Checkout GoDaddy Actions repo. # Checkout shared actions repository gd-actions
        run: echo "Checkout GoDaddy Actions repo."
      - name: Run Tartufo Scan.
        run: |
          echo Running Tartufo using PAT token ${{ secrets.REPO_PAT_TOKEN }}

  unit-test:
    needs: tartufo-job
    runs-on: ubuntu-latest
    env:
      FAVORITE_COLOR: ${{ secrets.FAVORITE_COLOR }}
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository https://github.com/actions/checkout/commits/main
      - name: Set up Python 3.8
        uses: actions/setup-python@41b7212b1668f5de9d65e9c82aa777e6bbedb3a8
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pip install -r requirements.txt
          python -m unittest -v
          echo What is your Favorite Color?
          echo $FAVORITE_COLOR
          echo blue? oh ok.

  deploy:
    needs: unit-test
    runs-on: self-hosted
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository https://github.com/actions/checkout/commits/main
      - name: Logging into AWS
        run: |
          echo Using DEV_AWS_ACCESS_KEY_ID ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          echo Using DEV_AWS_SECRET_ACCESS_KEY ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          echo Using DEV_AWS_ROLE_ARN ${{ secrets.DEV_AWS_ROLE_ARN }}
      - name: Deploying to dev
        run: |
          echo Deploying...
          echo Deployed!
