name: dotnet hello world
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: [non-pci,global-security]
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Set up .NET Core
        uses: actions/setup-dotnet@9211491ffb35dd6a6657ca4f45d43dfe6e97c829
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: create project
        run: |
          dotnet new console -o MyApp

      - name: run dotnet project
        run: |
          cd MyApp && dotnet run
