name: Follow up on Always Run Workflow

on:
  workflow_run:
    workflows: ["Always Run Workflow"]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "Step #1 - Print secret"
        run: echo PAT = ${{ secrets.REPO_PAT_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository https://github.com/actions/checkout/commits/main
      - name: Set up Python 3.8
        uses: actions/setup-python@41b7212b1668f5de9d65e9c82aa777e6bbedb3a8
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pip install -r requirements.txt
          python -m unittest -v
