name: "Manual Actions"

on:
  workflow_dispatch:
    inputs:
      gd_org: # which GoDaddy Org to take action on
        description: gd_org
        required: true
        type: choice
        options:
          - non-pci
      aws_env: # which AWS environment to take action on
        description: aws_env
        required: true
        type: choice
        options:
          # - dev-private
          - prod
      aws_region: # which region to take action on
        description: aws_region
        required: true
        type: choice
        options:
          - us-west-2
      action_to_take: # what to do
        description: action_to_take
        required: true
        type: choice
        options:
          - launch
          - delete
      target_scope:
        description: target_scope
        required: true
        type: string

jobs:
  take_action:
    environment: ${{ github.event.inputs.gd_org }}-${{ github.event.inputs.aws_env }}
    runs-on: ["${{ github.event.inputs.gd_org }}", global-security]
    steps:

      - name: Check out repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@1417e62aeacec5e7fbe447bb7712d50847507342
        with:
          aws-region: ${{ github.event.inputs.aws_region }}
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - name: Validate Sceptre stacks in specified region and environment
        run: |
          source ./env/${{ github.event.inputs.gd_org }}/${{ github.event.inputs.aws_env }}/${{ github.event.inputs.aws_region }}.env
          make validate

      - name: Act on Sceptre stacks in specified region and environment
        run: |
          source ./env/${{ github.event.inputs.gd_org }}/${{ github.event.inputs.aws_env }}/${{ github.event.inputs.aws_region }}.env
          make gha-manual-action-target ACTION_TO_TAKE="${{ github.event.inputs.action_to_take }}" TARGET_SCOPE="${{ github.event.inputs.target_scope }}"
