name: "Test install"
on:
  workflow_dispatch:

jobs:
  run_test:
    runs-on: [self-hosted, non-pci, deploy]
    environment: non-pci-dev-private
    steps:
      - name: Check out repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@1417e62aeacec5e7fbe447bb7712d50847507342
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-skip-session-tagging: true
          role-duration-seconds: 900
      - id: get_values
        run: |
          readonly TEAM_NAME="$(aws ssm get-parameter --name '/AdminParams/Team/Name' | jq --raw-output '.Parameter.Value')"
          readonly REGION_SPECIFIER="$(printf '${{ inputs.aws_region }}' | tr -d -- '-')"
          echo "::set-output name=executables_bucket::gd-${TEAM_NAME}-cicd-${{ inputs.gd_org }}-assets-executables-${REGION_SPECIFIER}"

      - name: Check out repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Install Helm
        uses: gdcorp-actions/install-executable-from-s3@74a2d96a079d750b09eba59abb1327391a723b94
        with:
          bucket: ${{ steps.get_values.outputs.executables_bucket }}
          executable: helm
          postfix: v3.9.4
          checksum: d7b04222b47873191178f1afb4338e31f7b1ff0bc47bbb582b49750aed3a4c38  # SHA-256

      - name: check_version
        id: check_version
        run: |
          helm version
  # notify:
  #   name: Starting Build
  #   uses: gdcorp-infosec/product-security-github/reusable/notify.yaml@829aeddb0862a97a9be4568a4f30721607564325
  #   with:
  #     gd_org: non-pci
  #     status: unknown
  #     subject: demo action
  #     message: |-
  #       *JOB*: testing
